name: Main Workflow

on: push

jobs:
  build:
    name: Lint and Test

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install .[test]

      - name: Check Documentation with Pydocstyle
        run: pydocstyle thermometer/* test.py --verbose

      - name: Lint with Black if > 3.5
        if: matrix.python-version > 3.5
        run: black ./thermometer/ test.py --check --verbose

      - name: Run unit tests with Pytest
        run: pytest test.py --verbose

      - name: Check that the temperature CLT is installed
        run: which temperature
